// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/khmer-todo/KhmerTodo.tsx": () => import("../components/mockups/khmer-todo/KhmerTodo.tsx")
};

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Check, Circle, ClipboardList, Leaf, Plus, RotateCcw, Trash2 } from "lucide-react";

type Filter = "all" | "active" | "completed";
type Task = { id: number; text: string; completed: boolean };

const STORAGE_KEY = "khmer-task-notebook-v1";
const starterTasks: Task[] = [
  { id: 1, text: "ទិញបន្លែសម្រាប់ម្ហូបល្ងាច", completed: false },
  { id: 2, text: "ហៅទូរស័ព្ទទៅម្តាយ", completed: false },
  { id: 3, text: "អានសៀវភៅ ២០ នាទី", completed: true },
];

export function KhmerTodo() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [text, setText] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      setTasks(stored ? JSON.parse(stored) : starterTasks);
    } catch {
      setTasks(starterTasks);
    }
    setReady(true);
  }, []);

  useEffect(() => {
    if (ready) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks));
  }, [tasks, ready]);

  const visibleTasks = useMemo(
    () => tasks.filter((task) => filter === "all" || (filter === "active" ? !task.completed : task.completed)),
    [tasks, filter],
  );
  const activeCount = tasks.filter((task) => !task.completed).length;
  const completedCount = tasks.length - activeCount;

  function addTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const clean = text.trim();
    if (!clean) return;
    setTasks((current) => [{ id: Date.now(), text: clean, completed: false }, ...current]);
    setText("");
  }

  function toggleTask(id: number) {
    setTasks((current) => current.map((task) => task.id === id ? { ...task, completed: !task.completed } : task));
  }

  function removeTask(id: number) {
    setTasks((current) => current.filter((task) => task.id !== id));
  }

  function clearCompleted() {
    setTasks((current) => current.filter((task) => !task.completed));
  }

  const filters: { key: Filter; label: string }[] = [
    { key: "all", label: "ទាំងអស់" },
    { key: "active", label: "កំពុងធ្វើ" },
    { key: "completed", label: "បានបញ្ចប់" },
  ];

  return (
    <main
      className="min-h-[100dvh] w-full px-4 py-6 text-[#3d4439] sm:px-8 sm:py-10"
      style={{
        fontFamily: "'Noto Sans Khmer', 'Khmer OS', system-ui, sans-serif",
        background: "radial-gradient(circle at 12% 0%, #fff5df 0, transparent 34%), #f5efe3",
      }}
    >
      <style>{`
        @keyframes khmer-in { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
        .khmer-in { animation: khmer-in .55s ease-out both; }
        .task-row { transition: transform .2s ease, background-color .2s ease, border-color .2s ease; }
        .task-row:hover { transform: translateX(2px); background-color: #fffdf8; border-color: #d7cdb9; }
      `}</style>
      <section className="mx-auto max-w-2xl">
        <header className="khmer-in mb-8 flex items-start justify-between">
          <div>
            <div className="mb-4 flex items-center gap-2 text-[#8b7658]">
              <span className="flex h-9 w-9 items-center justify-center rounded-2xl bg-[#e7dfcf]">
                <Leaf size={18} strokeWidth={1.8} />
              </span>
              <span className="text-xs font-semibold tracking-[0.18em]">កំណត់ត្រាប្រចាំថ្ងៃ</span>
            </div>
            <h1 className="text-[2rem] font-semibold leading-tight tracking-[-0.04em] text-[#384132] sm:text-[2.65rem]">
              បញ្ជីកិច្ចការ<span className="text-[#b27d50]">។</span>
            </h1>
            <p className="mt-2 text-sm text-[#8d8b7e]">រៀបចំថ្ងៃនេះ ឲ្យមានភាពស្ងប់ស្ងាត់ជាងមុន</p>
          </div>
          <div className="mt-1 hidden rounded-full border border-[#ded5c5] bg-[#fbf7ee] px-3 py-1.5 text-xs text-[#918b7c] sm:block">
            {new Intl.DateTimeFormat("km-KH", { weekday: "long", day: "numeric", month: "long" }).format(new Date())}
          </div>
        </header>

        <form onSubmit={addTask} className="khmer-in mb-6 flex items-center gap-2 rounded-[1.35rem] border border-[#ddd2bf] bg-[#fffaf1] p-2 shadow-[0_10px_30px_rgba(115,93,58,0.06)]" style={{ animationDelay: "80ms" }}>
          <label htmlFor="new-task" className="sr-only">បន្ថែមកិច្ចការ</label>
          <input
            id="new-task"
            value={text}
            onChange={(event) => setText(event.target.value)}
            placeholder="តើមានអ្វីត្រូវធ្វើ?"
            className="min-w-0 flex-1 bg-transparent px-4 py-3 text-[15px] text-[#3d4439] outline-none placeholder:text-[#b5ad9d]"
          />
          <button type="submit" aria-label="បន្ថែមកិច្ចការ" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#52604d] text-[#fffaf1] transition-transform hover:scale-[1.04] active:scale-95 disabled:cursor-not-allowed disabled:opacity-40" disabled={!text.trim()}>
            <Plus size={21} />
          </button>
        </form>

        <div className="khmer-in rounded-[1.6rem] border border-[#e0d6c5] bg-[#fbf8f0]/90 p-4 shadow-[0_16px_45px_rgba(115,93,58,0.07)] sm:p-6" style={{ animationDelay: "150ms" }}>
          <div className="mb-5 flex flex-wrap items-center justify-between gap-3 border-b border-[#e9e1d2] pb-4">
            <div>
              <h2 className="text-base font-semibold text-[#4a5144]">កិច្ចការរបស់អ្នក</h2>
              <p className="mt-1 text-xs text-[#9b9688]">{activeCount === 0 ? "ថ្ងៃនេះបានសម្រេចគ្រប់យ៉ាងហើយ" : `នៅសល់ ${activeCount} កិច្ចការ`}</p>
            </div>
            <div className="flex rounded-xl bg-[#f0eadd] p-1" role="tablist" aria-label="ត្រងកិច្ចការ">
              {filters.map((item) => (
                <button
                  key={item.key}
                  type="button"
                  role="tab"
                  aria-selected={filter === item.key}
                  onClick={() => setFilter(item.key)}
                  className={`rounded-lg px-2.5 py-1.5 text-xs transition-all sm:px-3 ${filter === item.key ? "bg-[#fffaf1] font-semibold text-[#52604d] shadow-sm" : "text-[#9b9688] hover:text-[#62685c]"}`}
                >
                  {item.label}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            {!ready ? (
              [1, 2, 3].map((item) => <div key={item} className="h-[58px] animate-pulse rounded-xl bg-[#eee7da]" />)
            ) : visibleTasks.length === 0 ? (
              <div className="rounded-2xl border border-dashed border-[#d9cfbd] bg-[#fdfaf3] px-5 py-12 text-center">
                <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl bg-[#ebe5d7] text-[#a18d6e]"><ClipboardList size={22} strokeWidth={1.6} /></div>
                <p className="text-sm font-semibold text-[#686e61]">{filter === "completed" ? "មិនទាន់មានកិច្ចការដែលបានបញ្ចប់" : "បញ្ជីរបស់អ្នកទំនេរ"}</p>
                <p className="mt-1 text-xs text-[#aaa292]">សរសេរកិច្ចការថ្មីមួយ ដើម្បីចាប់ផ្តើម</p>
              </div>
            ) : (
              visibleTasks.map((task) => (
                <div key={task.id} className="task-row group flex items-center gap-3 rounded-xl border border-transparent bg-[#f5f0e6] px-3 py-3">
                  <button type="button" onClick={() => toggleTask(task.id)} aria-label={task.completed ? "សម្គាល់ថាមិនទាន់បញ្ចប់" : "សម្គាល់ថាបានបញ្ចប់"} className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full transition-all ${task.completed ? "bg-[#71806b] text-[#fffaf1]" : "border-[1.5px] border-[#b9b4a5] text-transparent hover:border-[#71806b]"}`}>
                    {task.completed ? <Check size={14} strokeWidth={2.5} /> : <Circle size={15} />}
                  </button>
                  <span className={`flex-1 text-sm leading-6 ${task.completed ? "text-[#aaa496] line-through decoration-[#b9b2a2]" : "text-[#545a4e]"}`}>{task.text}</span>
                  <button type="button" onClick={() => removeTask(task.id)} aria-label={`លុប ${task.text}`} className="flex h-8 w-8 items-center justify-center rounded-lg text-[#b5ad9d] opacity-0 transition-all hover:bg-[#eee1d6] hover:text-[#a36f59] group-hover:opacity-100 focus:opacity-100">
                    <Trash2 size={16} />
                  </button>
                </div>
              ))
            )}
          </div>

          <footer className="mt-5 flex items-center justify-between border-t border-[#e9e1d2] pt-4 text-xs text-[#9b9688]">
            <span>{tasks.length} កិច្ចការ សរុប</span>
            {completedCount > 0 && <button type="button" onClick={clearCompleted} className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 transition-colors hover:bg-[#f0e8dc] hover:text-[#8f674f]"><RotateCcw size={13} /> លុបកិច្ចការដែលបានបញ្ចប់</button>}
          </footer>
        </div>
        <p className="mt-6 text-center text-[11px] text-[#aaa394]">កិច្ចការរបស់អ្នកត្រូវបានរក្សាទុកដោយស្វ័យប្រវត្តិ</p>
      </section>
    </main>
  );
}
